# Generated by Django 5.2.8 on 2025-11-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_count', models.IntegerField()),
                ('avg_flowrate', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('type_distribution', models.JSONField()),
            ],
        ),
    ]
